=== NataliaDz/XML-DTD/Orlando/musica.dtd
<!ELEMENT estudio (canciones)>
<!ELEMENT canciones (cancion+)>
<!ELEMENT cancion ( titulo, artista, album, duracion)>
<!ATTLIST cancion id_cancion ID #REQUIRED>
<!ELEMENT categoria (#PCDATA)>
<!ATTLIST cancion categoria (rock | pop | jazz) "rock"> 
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT artista (#PCDATA)>
<!ELEMENT album (#PCDATA)>
<!ELEMENT duracion  (#PCDATA)>

=== NataliaDz/XML-DTD/Orlando/musica.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE estudio PUBLIC "public-id" "musica.dtd">

<estudio>
    <canciones>
        <cancion id_cancion="c-001" categoria="rock">
            <titulo>Propuesta</titulo>
            <artista>Buena Fe</artista>
            <album>Corazonero</album>
            <duracion>3:15</duracion>
        </cancion>
        <cancion id_cancion="c-002" categoria="rock">
            <titulo>Así fue</titulo>
            <artista>Juan Grabiel, Isabel Pantoja</artista>
            <album>Desde Andalucía</album>
            <duracion>3:42</duracion>
        </cancion>
        <cancion id_cancion="c-003" categoria="rock">
            <titulo>Copacabana</titulo>
            <artista>Barry Manilow</artista>
            <album>Even Now</album>
            <duracion>4:07</duracion>
        </cancion>
    </canciones>

</estudio>
